ci: temporarilly pin the rbs version for JRuby (#345)
An error occurred while installing rbs (4.0.3), and Bundler cannot
continue.

```
In Gemfile:
  rdoc was resolved to 8.0.0, which depends on
    rbs
Error: The process '/home/runner/.rubies/jruby-10.1.0.0/bin/bundle' failed with exit code 5
```

- https://github.com/ruby/rdoc/issues/1746